name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Byte compile
      run: 'emacs -Q --batch --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile geoip.el'
    - name: Run tests
      run: |
        curl -s --remote-name-all https://raw.githubusercontent.com/maxmind/MaxMind-DB/master/test-data/{GeoIP2-Anonymous-IP-Test,GeoIP2-Country-Test}.mmdb
        emacs -Q --batch -L . -l geoip-tests -f ert-run-tests-batch-and-exit
